# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative "./Constants"
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

desc "Update Localization strings from POEditor"
lane :appStrings do
  Dir.chdir("..") do
  UI.message "Fetching localization files from POEditor.com..."
  sh("poesie -t #{POEDITOR_API_TOKEN} -p #{POEDITOR_PROJECT_ID} -l en -i 'PaybackPackage/Sources/Localization/Resources/en.lproj/Localizable.strings'")
  sh("poesie -t #{POEDITOR_API_TOKEN} -p #{POEDITOR_PROJECT_ID} -l de -i 'PaybackPackage/Sources/Localization/Resources/de.lproj/Localizable.strings'")
  sh("poesie -t #{POEDITOR_API_TOKEN} -p #{POEDITOR_PROJECT_ID} -l pl -i 'PaybackPackage/Sources/Localization/Resources/pl.lproj/Localizable.strings'")
  end
end